### ISSUE TITLE
Support code blocks

### ISSUE THREAD

**Issue by ruv** [martijnvanduijneveldt/markdown-diff#11]
What do you think to support diff for code blocks?

For example:

```
const v1="```\na\nb\nc\n```"
const v2="```\na\nb\nd\n```"

const res = markdownDiff(v1, v2)

console.log( res )
```

Actual result:
```
    ```
    a
    b
    <del>c</del><ins>d</ins>
    ```
```

Expected result:
```
    ```
      a
      b
    - c
    + d
    ```
```

**Comment by martijnvanduijneveldt** [comment]
Hi,
Some basic support has been added with ac45dcd2cdfad2ee6ded4e073f71d0d7154b201d

**Comment by ruv** [comment]
Thank you, it works!

But, if a line in a code block is not changed, it should be [prefixed with two spaces](https://github.com/martijnvanduijneveldt/markdown-diff/commit/ac45dcd2cdfad2ee6ded4e073f71d0d7154b201d#r80484372). Otherwise, lines that start with a plus or mines sign are not distinguishable from the changed lines.

**Comment by martijnvanduijneveldt** [comment]
Thanks for the feedback, added the two spaces in case there is any add/remove in the code block
